dist: trusty
language: node_js
node_js:
- '11'
script: sh -c 'cd generator && yarn && yarn generate'
cache: yarn
branches:
  only:
  - develop
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: develop
